### ISSUE TITLE
Build Fails for Unknown Reason

### ISSUE THREAD

**Issue by achintverma** [mgechev/angular2-simple-build#2]
Hello, thanks for your article on bundling Angular2 apps. I first tried to bundle my app. Later I clone this repo and tried it again to see if it works but it's giving me exact same error. Please see npm log below. 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build_prod' ]
2 info using npm@3.10.3
3 info using node@v6.4.0
4 verbose run-script [ 'prebuild_prod', 'build_prod', 'postbuild_prod' ]
5 info lifecycle angular2-min@1.0.0~prebuild_prod: angular2-min@1.0.0
6 silly lifecycle angular2-min@1.0.0~prebuild_prod: no script for prebuild_prod, continuing
7 info lifecycle angular2-min@1.0.0~build_prod: angular2-min@1.0.0
8 verbose lifecycle angular2-min@1.0.0~build_prod: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-min@1.0.0~build_prod: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/achintverma/pj/angular2-simple-build/node_modules/.bin:/usr/local/bin:/Users/achintverma/gapp/google-cloud-sdk/bin:/Users/achintverma/bin/:/usr/local/bin:/Applications/MAMP/bin/php/php5.6.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.composer/vendor/bin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/local/ec2/ec2-api-tools-1.7.5.1/bin
10 verbose lifecycle angular2-min@1.0.0~build_prod: CWD: /Users/achintverma/pj/angular2-simple-build
11 silly lifecycle angular2-min@1.0.0~build_prod: Args: [ '-c',
11 silly lifecycle   'npm run build && browserify -s main dist/main.js > dist/bundle.js && npm run minify' ]
12 silly lifecycle angular2-min@1.0.0~build_prod: Returned: code: 1  signal: null
13 info lifecycle angular2-min@1.0.0~build_prod: Failed to exec build_prod script
14 verbose stack Error: angular2-min@1.0.0 build_prod: `npm run build && browserify -s main dist/main.js > dist/bundle.js && npm run minify`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid angular2-min@1.0.0
16 verbose cwd /Users/achintverma/pj/angular2-simple-build
17 error Darwin 15.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build_prod"
19 error node v6.4.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error angular2-min@1.0.0 build_prod: `npm run build && browserify -s main dist/main.js > dist/bundle.js && npm run minify`
22 error Exit status 1
23 error Failed at the angular2-min@1.0.0 build_prod script 'npm run build && browserify -s main dist/main.js > dist/bundle.js && npm run minify'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-min package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build && browserify -s main dist/main.js > dist/bundle.js && npm run minify
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-min
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-min
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by mgechev** [comment]
This is not intended for usage but only a sample for the blog post. For production ready starter, I'd recommend you [angular2-seed](https://github.com/mgechev/angular2-seed).
