### ISSUE TITLE
npm run build_prod failed

### ISSUE THREAD

**Issue by bymw1990** [mgechev/angular2-simple-build#3]
Hi, first of all thanks for put these instructions up. but unfortunately I got an error when running the prod_build.
(I am using windows so I changed the clean task to "del /Q dist", which worked out ok)

Following is what reported in npm-debug.log (sorry I don't know how to make following issue reported look prettier):
<p>
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Users\u0479064\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build_prod' ]
2 info using npm@3.10.8
3 info using node@v4.5.0
4 verbose run-script [ 'prebuild_prod', 'build_prod', 'postbuild_prod' ]
5 info lifecycle angular2-min@1.0.0~prebuild_prod: angular2-min@1.0.0
6 silly lifecycle angular2-min@1.0.0~prebuild_prod: no script for prebuild_prod, continuing
7 info lifecycle angular2-min@1.0.0~build_prod: angular2-min@1.0.0
8 verbose lifecycle angular2-min@1.0.0~build_prod: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-min@1.0.0~build_prod: PATH: C:\Users\u0479064\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Projects Angular 2\angular2-simple-build\node_modules.bin;C:/Program Files/Java/jre1.8.0_101/bin/server;C:/Program Files/Java/jre1.8.0_101/bin;C:/Program Files/Java/jre1.8.0_101/lib/amd64;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\CCM;C:\Windows\CCM;C:\Windows\CCM;C:\Windows\CCM;C:\Windows\CCM;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\CCM;C:\Windows\CCM;C:\Windows\CCM;C:\Windows\CCM;C:\Windows\CCM;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Users\u0479064\AppData\Roaming\npm;C:\Windows\system32;
10 verbose lifecycle angular2-min@1.0.0~build_prod: CWD: C:\Projects Angular 2\angular2-simple-build
11 silly lifecycle angular2-min@1.0.0~build_prod: Args: [ '/d /s /c',
11 silly lifecycle   'npm run build && browserify -s main dist/main.js > dist/bundle.js && npm run minify' ]
12 silly lifecycle angular2-min@1.0.0~build_prod: Returned: code: 1  signal: null
13 info lifecycle angular2-min@1.0.0~build_prod: Failed to exec build_prod script
14 verbose stack Error: angular2-min@1.0.0 build_prod: `npm run build && browserify -s main dist/main.js > dist/bundle.js && npm run minify`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\u0479064\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\u0479064\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:829:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid angular2-min@1.0.0
16 verbose cwd C:\Projects Angular 2\angular2-simple-build
17 error Windows_NT 6.1.7601
18 error argv "C:\Program Files\nodejs\node.exe" "C:\Users\u0479064\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "run" "build_prod"
19 error node v4.5.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error angular2-min@1.0.0 build_prod: `npm run build && browserify -s main dist/main.js > dist/bundle.js && npm run minify`
22 error Exit status 1
23 error Failed at the angular2-min@1.0.0 build_prod script 'npm run build && browserify -s main dist/main.js > dist/bundle.js && npm run minify'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-min package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build && browserify -s main dist/main.js > dist/bundle.js && npm run minify
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-min
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-min
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by mgechev** [comment]
This is not intended for usage but only a sample for the blog post. For production ready starter, I'd recommend you [angular2-seed](https://github.com/mgechev/angular2-seed).
