### ISSUE TITLE
help

### ISSUE THREAD

**Issue by kevinablett** [mgechev/angular2-simple-build#6]
Not sure if i have done something wrong, but i'm trying to get a basic version of angular bundling working.

I download this source code, npm i, runs succesfully but when i run npm run build_prod it fails. It failed on almost every step so i deleted all items but this line, just to get an idea on how this works. 

    "build_prod": "npm run browserify -s main dist/main.js > dist/bundle.js"

That also fails with this error, any help would be great?

16 verbose cwd C:\Users\kevin\Downloads\angular2-simple-build-master\angular2-simple-build-master
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build_prod"
19 error node v6.9.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error angular2-min@1.0.0 build_prod: `npm run browserify -s main dist/main.js > dist/bundle.js`
22 error Exit status 1
23 error Failed at the angular2-min@1.0.0 build_prod script 'npm run browserify -s main dist/main.js > dist/bundle.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-min package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run browserify -s main dist/main.js > dist/bundle.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-min
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-min
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by mgechev** [comment]
@kevinablett this repository is no longer maintained. You can use Angular Seed or Angular CLI.
